config/routes.rb
Rails.application.routes.draw do
  
  get '/', to: 'home#index'
  get 'login', to: 'user_sessions#new'
  get 'logout', to: 'user_sessions#destroy'
  get 'signup', to: 'users#new'

  resources :user_sessions, only: [ :new, :create, :destroy ]
  scope :admin do
    resources :users, except: :new
  end
  resources :projects do
    resources :domains, except: [ :index ] do
      resources :stories, except: [ :index ]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
  belongs_to :organisation
  has_many :projects
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    sanitised_params = user_params
    org_name = sanitised_params[:organisation]    
    sanitised_params.delete(:organisation)
    @user = User.new(sanitised_params)
    @user.organisation_id = get_organisation_id(org_name)
    @user.is_admin = is_admin(sanitised_params[:is_admin])
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:forename, :surname, :email, :password, :password_confirmation, :is_admin, :organisation)
    end

    def get_organisation_id(name)
      org = Organisation.where(:name => name).first
      if org
        return org.id
      else
        add_organisation(name)
        get_organisation_id(name)
      end
    end

    def add_organisation(name)
      new_org = Organisation.new(:name => name)
      new_org.save
    end

    def is_admin(checkbox_value)
      if checkbox_value.to_i == 0 and User.all.last
        return 0
      else
        return 1
      end
    end
      
end

app/helpers/users_helper.rb
module UsersHelper
  def is_admin
    if current_user and current_user.is_admin == 1
      return true
    end
    false
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :forename %>
    <%= form.text_field :forename, id: :user_forename %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname, id: :user_surname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :user_password_confirmation %>
  </div>

<div class="field">
    <%= form.label :organisation %>
    <%= form.text_field :organisation, id: :organisation %>
  </div>
    
  <% if is_admin %>
    <div class="checkbox">
      <%= form.label "Is Admin?" %>
      <%= form.check_box :is_admin, id: :is_admin %>
    </div>
    <% end %>

    <br>
    
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Forename</th>
      <th>Surname</th>
      <th>Email</th>
      <th>Password</th>
      <th>Password confirmation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.forename %></td>
        <td><%= user.surname %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.password_confirmation %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', signup_path %>

app/views/users/new.html.erb
<h2>Sign up for an account and start organising your projects today!</h2>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Forename:</strong>
  <%= @user.forename %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @user.surname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Password confirmation:</strong>
  <%= @user.password_confirmation %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>