config/routes.rb
Rails.application.routes.draw do
  
  get '/', to: 'home#index'
  get 'login', to: 'user_sessions#new'
  get 'logout', to: 'user_sessions#destroy'
  get 'signup', to: 'users#new'

  resources :user_sessions, only: [ :new, :create, :destroy ]
  scope :admin do
    resources :users, except: :new
  end
  resources :projects do
    resources :domains, except: [ :index ] do
      resources :stories, except: [ :index ]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/domain.rb
class Domain < ApplicationRecord
  belongs_to :project
  has_many :stories
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: [:show, :edit, :update, :destroy]

  # GET /domains
  # GET /domains.json
  def index
    @domains = Domain.all
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
    @stories = Story.where(:domain_id => params[:id])
  end

  # GET /domains/new
  def new
    @domain = Domain.new
  end

  # GET /domains/1/edit
  def edit
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(domain_params)
    @domain.project_id = params[:project_id]

    respond_to do |format|
      if @domain.save
        format.html { redirect_to project_path(params[:project_id]), notice: 'Domain was successfully created.' }
        format.json { render :show, status: :created, location: @domain }
      else
        format.html { render :new }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domains/1
  # PATCH/PUT /domains/1.json
  def update
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { render :show, status: :ok, location: @domain }
      else
        format.html { render :edit }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain.destroy
    respond_to do |format|
      format.html { redirect_to project_path(params[:project_id]), notice: 'Domain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain
      @domain = Domain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def domain_params
      params.require(:domain).permit(:title)
    end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/_form.html.erb
<%= form_for [:project, @domain] do |form| %>
  <% if domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% domain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :domain_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/domains/edit.html.erb
<h1>Editing Domain</h1>

<%= render 'form', domain: @domain %>

<%= link_to 'Project', project_path(params[:project_id]) %> |
<%= link_to 'Back', project_domain_path(params[:project_id], @domain) %>

app/views/domains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Domains</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @domains.each do |domain| %>
    <tr>
        <td><%= domain.title %></td>
        <td><%= link_to 'Show', project_domain_path(domain.project_id, domain) %></td>
        <td><%= link_to 'Edit', edit_project_domain_path(:projects, domain) %></td>
        <td><%= link_to 'Destroy', project_domain_path(:projects, domain), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Domain', new_project_domain_path %>

app/views/domains/new.html.erb
<h1>New Domain</h1>

<%= render 'form', domain: @domain %>

<%= link_to 'Back', project_domains_path %>

app/views/domains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
 <strong>Title:</strong>
  <%= @domain.title %>
</p>


<%= link_to 'Edit', edit_project_domain_path(@domain) %> |
<%= link_to 'Back', project_path(params[:project_id]) %>


<p>
  <%= link_to 'New Story', new_project_domain_story_path(params[:project_id], @domain) %>
</p>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Actor</th>
      <th>Action</th>
      <th>Objective</th>
      <th>Notes</th>
      <th>How to test</th>
      <th>Definition of done</th>
      <th>Estimate</th>
      <th>Completion time</th>
      <th>Priority</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><strong><%= story.title %></strong></td>
        <td><%= story.actor %></td>
        <td><%= story.action %></td>
        <td><%= story.objective %></td>
        <td><%= story.notes %></td>
        <td><%= story.how_to_test %></td>
        <td><%= story.definition_of_done %></td>
        <td><%= story.estimate %></td>
        <td><%= story.completion_time %></td>
	<td><%= story.priority %></td>
	<td><%= story.completed %></td>
        <td><%= link_to 'View', project_domain_story_path(params[:project_id], params[:id], story) %></td>
        <td><%= link_to 'Edit', edit_project_domain_story_path(params[:project_id], params[:id], story) %></td>
        <td><%= link_to 'Destroy', project_domain_story_path(params[:project_id], params[:id], story), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>