config/routes.rb
Rails.application.routes.draw do
  
  get '/', to: 'home#index'
  get 'login', to: 'user_sessions#new'
  get 'logout', to: 'user_sessions#destroy'
  get 'signup', to: 'users#new'

  resources :user_sessions, only: [ :new, :create, :destroy ]
  scope :admin do
    resources :users, except: :new
  end
  resources :projects do
    resources :domains, except: [ :index ] do
      resources :stories, except: [ :index ]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :domain
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)
    @story.domain_id = params[:domain_id]

    respond_to do |format|
      if @story.save
        format.html { redirect_to project_domain_path(params[:project_id], params[:domain_id]), notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to project_domain_story_path(params[:project_id], params[:domain_id], @story), notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :actor, :action, :objective, :notes, :how_to_test, :definition_of_done, :estimate, :completion_time, :completed, :priority)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/.#index.html.erb
rob@elysium.5703:1506169153

app/views/stories/_form.html.erb
<%= form_for [:project, :domain, @story] do |form| %>
<% if story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :story_title %>
  </div>

  <div class="field">
    <label for="actor">As a...</label>
    <%= form.text_field :actor, id: :story_actor %>
  </div>

  <div class="field">
    <label for="action">I would like to...</label>
    <%= form.text_area :action, id: :story_action %>
  </div>

  <div class="field">
    <label for="objective">In order to...</label>
    <%= form.text_area :objective, id: :story_objective %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes, id: :story_notes %>
  </div>

  <div class="field">
    <%= form.label :how_to_test %>
    <%= form.text_area :how_to_test, id: :story_how_to_test %>
  </div>

  <div class="field">
    <%= form.label :definition_of_done %>
    <%= form.text_area :definition_of_done, id: :story_definition_of_done %>
  </div>

  <div class="field">
    <%= form.label :estimate %>
    <%= form.text_field :estimate, id: :story_estimate %>
  </div>

  <div class="field">
    <%= form.label :completion_time %>
    <%= form.text_field :completion_time, id: :story_completion_time %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.number_field :priority, id: :priority %>
  </div>

  <div class="checkbox">
    <label for="completed">Story completed?</label>
    <%= form.check_box :completed, id: :story_completed %>
  </div>

  <br>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Show', project_domain_story_path(params[:project_id], params[:domain_id], @story) %> |
<%= link_to 'Back', project_domain_story_path(params[:project_id], params[:domain_id], @story) %>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Actor</th>
      <th>Action</th>
      <th>Objective</th>
      <th>Notes</th>
      <th>How to test</th>
      <th>Definition of done</th>
      <th>Estimate</th>
      <th>Completion time</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.title %></td>
        <td><%= story.actor %></td>
        <td><%= story.action %></td>
        <td><%= story.objective %></td>
        <td><%= story.notes %></td>
        <td><%= story.how_to_test %></td>
        <td><%= story.definition_of_done %></td>
        <td><%= story.estimate %></td>
        <td><%= story.completion_time %></td>
        <td><%= story.completed %></td>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Back', new_project_domain_story_path(params[:project_id], params[:domain_id]) %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Actor:</strong>
  <%= @story.actor %>
</p>

<p>
  <strong>Action:</strong>
  <%= @story.action %>
</p>

<p>
  <strong>Objective:</strong>
  <%= @story.objective %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @story.notes %>
</p>

<p>
  <strong>How to test:</strong>
  <%= @story.how_to_test %>
</p>

<p>
  <strong>Definition of done:</strong>
  <%= @story.definition_of_done %>
</p>

<p>
  <strong>Estimate:</strong>
  <%= @story.estimate %>
</p>

<p>
  <strong>Completion time:</strong>
  <%= @story.completion_time %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @story.priority %>
</p>


<p>
  <strong>Completed:</strong>
  <%= @story.completed %>
</p>

<%= link_to 'Edit', edit_project_domain_story_path(params[:project_id], params[:domain_id], @story) %> |
<%= link_to 'Back', project_domain_path(params[:project_id], params[:domain_id]) %>